[build]
  command = "npm ci && npm run build"
  publish = "apps/dashboard/dist"
  functions = "netlify/functions"  # If using Netlify Functions

[build.environment]
  NODE_VERSION = "20.11.1"  # Lock to LTS version
  NPM_VERSION = "10.7.0"
  NODE_OPTIONS = "--openssl-legacy-provider"
  CI = "false"
  
  # Vite specific
  VITE = "true"
  VITE_APP_VERSION = "$GIT_COMMIT_REF"
  VITE_APP_BUILD_DATE = "$CURRENT_DATE"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  targetPort = 5173
  target = "esnext"

# Build processing
[build.processing]
  skip_processing = true
  css = { bundle = true, minify = true }
  js = { bundle = true, minify = true }
  html = { pretty_urls = true }
  images = { compress = true }

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers for all responses
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Modern CSP with nonce-based approach for scripts/styles
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
      style-src 'self' 'unsafe-inline' https:;
      img-src 'self' data: https:;
      font-src 'self' data: https:;
      connect-src 'self' https:;
      media-src 'self' https:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      block-all-mixed-content;
      upgrade-insecure-requests;
    """
    
    # Feature policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    
    # Security headers for modern browsers
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-site"
    
    # Performance
    X-DNS-Prefetch-Control = "on"

# Cache settings for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "*"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = "*", Country = "*"}

# Environment specific settings (if needed)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "development"
